# Generated by Django 5.2.16 on 2026-07-14 14:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "kind",
                    models.CharField(
                        choices=[("case", "Case"), ("contract", "Contract"), ("notice", "Notice")],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("reference_code", models.CharField(max_length=64, verbose_name="reference code")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("on_hold", "On hold"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                            ("received", "Received"),
                            ("under_review", "Under review"),
                            ("response_due", "Response due"),
                            ("responded", "Responded"),
                        ],
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("opened_on", models.DateField(blank=True, null=True, verbose_name="opened on")),
                ("closed_on", models.DateField(blank=True, null=True, verbose_name="closed on")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="archived at"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_matters",
                        to="organizations.membership",
                        verbose_name="archived by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_matters",
                        to="organizations.membership",
                        verbose_name="created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matters",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_matters",
                        to="organizations.membership",
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "matter",
                "verbose_name_plural": "matters",
                "ordering": ("reference_code",),
            },
        ),
        migrations.CreateModel(
            name="MatterAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "level",
                    models.CharField(
                        choices=[("view", "View"), ("edit", "Edit")],
                        max_length=8,
                        verbose_name="level",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="revoked at"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_matter_access",
                        to="organizations.membership",
                        verbose_name="granted by",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_grants",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matter_access_grants",
                        to="organizations.membership",
                        verbose_name="membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matter_access_grants",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "matter access",
                "verbose_name_plural": "matter access grants",
                "ordering": ("matter__reference_code", "membership__user__username"),
            },
        ),
        migrations.CreateModel(
            name="MatterRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("depends_on", "Depends on"),
                            ("supersedes", "Supersedes"),
                        ],
                        max_length=32,
                        verbose_name="relation type",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matter_relations",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relations",
                        to="matters.matter",
                        verbose_name="source matter",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relations",
                        to="matters.matter",
                        verbose_name="target matter",
                    ),
                ),
            ],
            options={
                "verbose_name": "matter relation",
                "verbose_name_plural": "matter relations",
                "ordering": ("source__reference_code", "target__reference_code"),
            },
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "reference_code"], name="matter_org_ref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(fields=["organization", "status"], name="matter_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(fields=["organization", "owner"], name="matter_org_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "kind", "status"], name="matter_org_kind_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matter",
            constraint=models.UniqueConstraint(
                fields=("organization", "reference_code"),
                name="matters_matter_unique_organization_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="matter",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="matters_matter_version_gte_1"
            ),
        ),
        migrations.AddIndex(
            model_name="matteraccess",
            index=models.Index(
                fields=["organization", "membership"], name="access_org_membership_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matteraccess",
            index=models.Index(fields=["matter", "revoked_at"], name="access_matter_revoked_idx"),
        ),
        migrations.AddConstraint(
            model_name="matteraccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("matter", "membership"),
                name="matters_access_unique_active_matter_membership",
            ),
        ),
        migrations.AddIndex(
            model_name="matterrelation",
            index=models.Index(fields=["organization", "source"], name="relation_org_source_idx"),
        ),
        migrations.AddIndex(
            model_name="matterrelation",
            index=models.Index(fields=["organization", "target"], name="relation_org_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="matterrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="matters_relation_source_not_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="matterrelation",
            constraint=models.UniqueConstraint(
                fields=("organization", "source", "target", "relation_type"),
                name="matters_relation_unique_org_source_target_type",
            ),
        ),
    ]
