# Generated by Django 5.2.16 on 2026-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0002_userinvitation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "kind", "priority"], name="matter_org_kind_prio_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "kind", "created_at"], name="matter_org_kind_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "kind", "opened_on"], name="matter_org_kind_opened_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(
                fields=["organization", "kind", "archived_at"], name="matter_org_kind_archive_idx"
            ),
        ),
    ]
