# Generated by Django 5.2.16 on 2026-07-14 15:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalCase",
            fields=[
                (
                    "matter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="legal_case",
                        serialize=False,
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("litigation", "Litigation"),
                            ("regulatory", "Regulatory"),
                            ("internal", "Internal"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="case type",
                    ),
                ),
                (
                    "court_or_authority",
                    models.CharField(blank=True, max_length=255, verbose_name="court or authority"),
                ),
                (
                    "filing_date",
                    models.DateField(blank=True, null=True, verbose_name="filing date"),
                ),
                ("outcome_summary", models.TextField(blank=True, verbose_name="outcome summary")),
            ],
            options={
                "verbose_name": "legal case",
                "verbose_name_plural": "legal cases",
                "ordering": ("matter__reference_code",),
                "indexes": [
                    models.Index(fields=["case_type"], name="case_type_idx"),
                    models.Index(fields=["filing_date"], name="case_filing_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("opposing", "Opposing party"),
                            ("court", "Court or authority"),
                            ("witness", "Witness"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "contact_summary",
                    models.CharField(blank=True, max_length=500, verbose_name="contact summary"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_parties",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parties",
                        to="cases.legalcase",
                        verbose_name="case",
                    ),
                ),
            ],
            options={
                "verbose_name": "case party",
                "verbose_name_plural": "case parties",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["organization", "role"], name="case_party_org_role_idx"),
                    models.Index(fields=["case", "role"], name="case_party_case_role_idx"),
                ],
            },
        ),
    ]
