# Generated by Django 5.2.16 on 2026-07-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("deadlines", "0001_initial"),
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalNotice",
            fields=[
                (
                    "matter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="notice",
                        serialize=False,
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                ("sender", models.CharField(max_length=255, verbose_name="sender")),
                ("received_date", models.DateField(verbose_name="received date")),
                ("response_deadline", models.DateTimeField(verbose_name="response deadline")),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("responded", "Responded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="response status",
                    ),
                ),
                (
                    "linked_deadline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_notice",
                        to="deadlines.deadline",
                        verbose_name="linked response deadline",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal notice",
                "verbose_name_plural": "legal notices",
                "ordering": ("matter__reference_code",),
                "indexes": [
                    models.Index(fields=["sender"], name="notice_sender_idx"),
                    models.Index(fields=["received_date"], name="notice_received_idx"),
                    models.Index(fields=["response_deadline"], name="notice_response_due_idx"),
                    models.Index(fields=["response_status"], name="notice_response_status_idx"),
                ],
            },
        ),
    ]
