# Generated by Django 5.2.16 on 2026-07-14 16:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("due_at", models.DateTimeField(verbose_name="due at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, verbose_name="reminder enabled"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_deadlines",
                        to="organizations.membership",
                        verbose_name="assignee",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_deadlines",
                        to="organizations.membership",
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_deadlines",
                        to="organizations.membership",
                        verbose_name="completed by",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deadlines",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deadlines",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "deadline",
                "verbose_name_plural": "deadlines",
                "ordering": ("due_at", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "due_at"],
                        name="deadline_org_status_due_idx",
                    ),
                    models.Index(
                        fields=["organization", "assignee", "status", "due_at"],
                        name="deadline_org_assignee_idx",
                    ),
                    models.Index(
                        fields=["organization", "matter", "status"], name="deadline_org_matter_idx"
                    ),
                    models.Index(fields=["priority"], name="deadline_priority_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="deadlines_deadline_version_gte_1",
                    )
                ],
            },
        ),
    ]
