# Generated by Django 5.2.16 on 2026-07-14 16:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("due_at", models.DateTimeField(blank=True, null=True, verbose_name="due at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to="organizations.membership",
                        verbose_name="assignee",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_tasks",
                        to="organizations.membership",
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_tasks",
                        to="organizations.membership",
                        verbose_name="completed by",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ("due_at", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "due_at"], name="task_org_status_due_idx"
                    ),
                    models.Index(
                        fields=["organization", "assignee", "status"], name="task_org_assignee_idx"
                    ),
                    models.Index(
                        fields=["organization", "matter", "status"], name="task_org_matter_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="tasks_task_version_gte_1"
                    )
                ],
            },
        ),
    ]
