# Generated by Django 5.2.16 on 2026-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0002_matter_matter_org_kind_prio_idx_and_more"),
        ("organizations", "0002_userinvitation"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organization", "assignee", "status", "due_at"],
                name="task_org_assignee_due_idx",
            ),
        ),
    ]
