# Generated by Django 5.2.16 on 2026-07-14 14:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("case.created", "Case created"),
                            ("case.updated", "Case updated"),
                            ("matter.archived", "Matter archived"),
                            ("matter.owner_changed", "Matter owner changed"),
                            ("matter.access_granted", "Matter access granted"),
                            ("matter.access_revoked", "Matter access revoked"),
                            ("contract.created", "Contract created"),
                            ("contract.updated", "Contract updated"),
                            ("notice.created", "Notice created"),
                            (
                                "notice.response_deadline_changed",
                                "Notice response deadline changed",
                            ),
                            ("deadline.created", "Deadline created"),
                            ("deadline.completed", "Deadline completed"),
                            ("task.created", "Task created"),
                            ("task.completed", "Task completed"),
                            ("document.upload_initiated", "Document upload initiated"),
                            ("document.upload_completed", "Document upload completed"),
                            ("document.available", "Document available"),
                            ("document.download_requested", "Document download requested"),
                            ("offboarding.executed", "Offboarding executed"),
                        ],
                        max_length=64,
                        verbose_name="action",
                    ),
                ),
                ("target_type", models.CharField(max_length=64, verbose_name="target type")),
                ("target_id", models.UUIDField(blank=True, null=True, verbose_name="target id")),
                (
                    "before_values",
                    models.JSONField(blank=True, default=dict, verbose_name="before values"),
                ),
                (
                    "after_values",
                    models.JSONField(blank=True, default=dict, verbose_name="after values"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=64, verbose_name="request id"),
                ),
                (
                    "actor_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_logs",
                        to="organizations.membership",
                        verbose_name="actor membership",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor user",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_logs",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_logs",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity log",
                "verbose_name_plural": "activity logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"], name="activity_org_created_idx"
                    ),
                    models.Index(
                        fields=["matter", "-created_at"], name="activity_matter_created_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="activity_action_created_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("event_type", models.CharField(max_length=128, verbose_name="event type")),
                (
                    "event_version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="event version"),
                ),
                ("aggregate_type", models.CharField(max_length=64, verbose_name="aggregate type")),
                ("aggregate_id", models.UUIDField(verbose_name="aggregate id")),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "available_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="available at"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="published at"),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="attempt count"),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, max_length=64, verbose_name="last error code"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "outbox event",
                "verbose_name_plural": "outbox events",
                "ordering": ("available_at", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["published_at", "available_at"], name="outbox_publish_ready_idx"
                    ),
                    models.Index(
                        fields=["organization", "event_type"], name="outbox_org_event_type_idx"
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"], name="outbox_aggregate_idx"
                    ),
                ],
            },
        ),
    ]
