# Generated by Django 5.2.16 on 2026-07-14 15:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("scope", models.CharField(max_length=128, verbose_name="scope")),
                ("key_hash", models.CharField(max_length=64, verbose_name="key hash")),
                ("request_hash", models.CharField(max_length=64, verbose_name="request hash")),
                (
                    "status",
                    models.CharField(
                        choices=[("started", "Started"), ("completed", "Completed")],
                        default="started",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="response status"
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(blank=True, default=dict, verbose_name="response body"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="organizations.membership",
                        verbose_name="actor membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "idempotency record",
                "verbose_name_plural": "idempotency records",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "actor_membership", "scope"],
                        name="idem_org_actor_scope_idx",
                    ),
                    models.Index(fields=["expires_at"], name="idem_expires_at_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "actor_membership", "scope", "key_hash"),
                        name="activity_idem_unique_org_actor_scope_key",
                    )
                ],
            },
        ),
    ]
