# Generated by Django 5.2.16 on 2026-07-14 17:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "object_key",
                    models.CharField(max_length=255, unique=True, verbose_name="object key"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                ("expected_size", models.PositiveBigIntegerField(verbose_name="expected size")),
                (
                    "expected_content_type",
                    models.CharField(max_length=127, verbose_name="expected content type"),
                ),
                (
                    "expected_checksum",
                    models.CharField(blank=True, max_length=128, verbose_name="expected checksum"),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("verifying", "Verifying"),
                            ("processing", "Processing"),
                            ("available", "Available"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=64, verbose_name="failure code"),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to="organizations.membership",
                        verbose_name="requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "upload session",
                "verbose_name_plural": "upload sessions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "expires_at"],
                        name="upload_org_status_exp_idx",
                    ),
                    models.Index(
                        fields=["matter", "status", "-created_at"], name="upload_matter_status_idx"
                    ),
                    models.Index(
                        fields=["requested_by", "status", "expires_at"],
                        name="upload_requester_status_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expected_size__gt", 0)),
                        name="documents_upload_expected_size_gt_0",
                    )
                ],
            },
        ),
    ]
