# Generated by Django 5.2.16 on 2026-07-14 17:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("matters", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "object_key",
                    models.CharField(max_length=255, unique=True, verbose_name="object key"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                ("content_type", models.CharField(max_length=127, verbose_name="content type")),
                ("size", models.PositiveBigIntegerField(verbose_name="size")),
                ("checksum", models.CharField(blank=True, max_length=128, verbose_name="checksum")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("available", "Available"),
                            ("failed", "Failed"),
                            ("revoked", "Revoked"),
                        ],
                        default="processing",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "available_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="available at"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="revoked at"),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_documents",
                        to="organizations.membership",
                        verbose_name="revoked by",
                    ),
                ),
                (
                    "upload_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document",
                        to="documents.uploadsession",
                        verbose_name="upload session",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to="organizations.membership",
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="doc_org_status_created_idx",
                    ),
                    models.Index(
                        fields=["matter", "status", "-created_at"], name="doc_matter_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("size__gt", 0)), name="documents_document_size_gt_0"
                    )
                ],
            },
        ),
    ]
