# Generated by Django 5.2.16 on 2026-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document"),
        ("matters", "0001_initial"),
        ("organizations", "0002_userinvitation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "original_filename"], name="doc_org_filename_idx"
            ),
        ),
    ]
