# Generated by Codex on 2026-07-15

from django.db import migrations, models
from django.db.models import F


def migrate_document_rows(apps, schema_editor):
    document = apps.get_model("documents", "Document")
    document.objects.filter(status="processing").update(status="pending_upload")
    document.objects.filter(status="revoked").update(status="cancelled")
    document.objects.filter(status="available", actual_size__isnull=True).update(
        actual_size=F("expected_size"),
        actual_checksum=F("expected_checksum"),
    )


def reverse_document_rows(apps, schema_editor):
    document = apps.get_model("documents", "Document")
    document.objects.filter(status="pending_upload").update(status="processing")
    document.objects.filter(status="cancelled").update(status="revoked")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_doc_org_filename_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="size",
            new_name="expected_size",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="checksum",
            new_name="expected_checksum",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="available_at",
            new_name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="document",
            name="expected_size",
            field=models.PositiveBigIntegerField(verbose_name="expected size"),
        ),
        migrations.AlterField(
            model_name="document",
            name="expected_checksum",
            field=models.CharField(blank=True, max_length=128, verbose_name="expected checksum"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="uploaded at"),
        ),
        migrations.RemoveConstraint(
            model_name="document",
            name="documents_document_size_gt_0",
        ),
        migrations.RemoveField(
            model_name="document",
            name="upload_session",
        ),
        migrations.RemoveField(
            model_name="document",
            name="revoked_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="revoked_at",
        ),
        migrations.AddField(
            model_name="document",
            name="actual_size",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                verbose_name="actual size",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="actual_checksum",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="actual checksum",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="etag",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="ETag"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="upload_expires_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="upload expires at",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="failure_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="failure code",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_document_rows, reverse_document_rows),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_upload", "Pending upload"),
                    ("verifying", "Verifying"),
                    ("available", "Available"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_upload",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size__gt", 0)),
                name="documents_document_expected_size_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "status", "upload_expires_at"],
                name="doc_org_status_exp_idx",
            ),
        ),
        migrations.DeleteModel(
            name="UploadSession",
        ),
    ]
