# Generated by Django 5.2.16 on 2026-07-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "matter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="contract",
                        serialize=False,
                        to="matters.matter",
                        verbose_name="matter",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("vendor", "Vendor"),
                            ("employment", "Employment"),
                            ("nda", "NDA"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="contract type",
                    ),
                ),
                ("counterparty", models.CharField(max_length=255, verbose_name="counterparty")),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="expiration date"),
                ),
                (
                    "renewal_date",
                    models.DateField(blank=True, null=True, verbose_name="renewal date"),
                ),
                ("key_terms", models.JSONField(blank=True, default=dict, verbose_name="key terms")),
            ],
            options={
                "verbose_name": "contract",
                "verbose_name_plural": "contracts",
                "ordering": ("matter__reference_code",),
                "indexes": [
                    models.Index(fields=["contract_type"], name="contract_type_idx"),
                    models.Index(fields=["counterparty"], name="contract_counterparty_idx"),
                    models.Index(fields=["effective_date"], name="contract_effective_idx"),
                    models.Index(fields=["expiration_date"], name="contract_expiration_idx"),
                    models.Index(fields=["renewal_date"], name="contract_renewal_idx"),
                ],
            },
        ),
    ]
