# Generated by Django 5.2.16 on 2026-07-14 14:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.organizations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[apps.organizations.models.validate_timezone],
                        verbose_name="timezone",
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("en", "English"), ("fa", "Persian")],
                        default="en",
                        max_length=2,
                        verbose_name="default language",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("legal_admin", "Legal admin"),
                            ("legal_manager", "Legal manager"),
                            ("legal_counsel", "Legal counsel"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("offboarded", "Offboarded"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="joined at"
                    ),
                ),
                (
                    "offboarded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="offboarded at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
                "ordering": ("organization__name", "user__username"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "role"],
                        name="org_membership_status_role_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="organizations_membership_unique_organization_user",
                    )
                ],
            },
        ),
    ]
